#Packages to install:
install.packages("MASS")
install.packages("pracma")
install.packages("ggplot2")
install.packages("gganimate")
install.packages("fractaldim")
install.packages("fitdistrplus")
install.packages("gifski")
install.packages("fBasics")
install.packages("stabledist")
install.packages("car")
